# CV analysis per member, keyed by email as it appears in data/members.xlsx (case-insensitive).
# Levels: Beginner < Developing < Intermediate < Advanced. Members without an analyzable CV are left out
# and show as "Incomplete" on the roster.

ANALYSIS = {
    "ibrahim.abualg@gmail.com": {
        "en": "Ibrahim Abu Alghayth",
        "level": "Advanced",
        "focus": ["Data & Bioinformatics", "Full-stack", "UI/UX"],
        "skills": ["Python", "Java", "JavaScript", "C", "R", "SQL (basic)", "HTML/CSS", "Linux/WSL", "Git", "Figma", "RStudio"],
        "projects": [
            "TDP-43 RNA-seq analysis: FastQC, fastp, Salmon, DESeq2 pipeline; 95.42% mapping rate, 23 DEGs found",
            "Eco Zone Hackathon: AI-driven environmental awareness prototype with automated change detection",
            "Cloud booking app: accessibility-focused design, user research with 55 participants",
            "FlowPay (digital payments UI) and HealthFy (desktop medical records app)",
        ],
        "experience": [
            "KAUST Academy Bioinformatics Advanced Program, with distinction",
            "Website testing contributor, UJ Innovate Platform",
            "Events member, Drone Club · Media & Design member, GDG",
        ],
        "summary": "Broadest technical profile on the track. Took a real data pipeline end to end (RNA-seq, 95% mapping rate) and pairs it with app building, UX research and functional testing. Picks up new toolchains quickly.",
        "strengths": "Python and data analysis, research discipline, testing experience, wide language range.",
        "gaps": "SQL and web are listed as basic. Most app projects read as design or prototype work more than deployed code.",
        "next": "Good candidate to run a Python or data session, or mentor a beginner pair. Push toward one shipped, deployed app to match the depth of the data work.",
        "links": {"GitHub": "https://github.com/Ibrah1m1", "LinkedIn": "https://www.linkedin.com/in/ibrahim-eissa-5aa895283/"},
        "notes": ["GPA on CV is 4.85; sheet says 4.88."],
    },
    "osama.a.alghamdi707@gmail.com": {
        "en": "Osama Al-Ghamdi",
        "level": "Advanced",
        "focus": ["Mobile", "Full-stack", "Game dev", "Research"],
        "skills": ["Java", "C#", "Python", "JavaScript", "SQL", "Android", "Firebase", "React", "Unity", "Git", "Jira", "Figma", "LaTeX", "Agile/Scrum"],
        "projects": [
            "RepoCare: Android + Firebase app for medical reports; 1st place, Graduation Project in 3 Minutes",
            "ThinkUp: React + Firebase study-session platform with real-time data and AI summaries",
            "AirQuest: Riyadh Air Global Hackathon prototype (AI, GPS, AR)",
            "15 Min: 3D escape room game in Unity (Tuwaiq Academy program)",
        ],
        "experience": [
            "Co-author, VidSumEval, accepted paper at ASE 2026 (Tools & Datasets)",
            "Student developer, University of Jeddah (Mar–May 2025)",
            "Event organizer, Jeddah Season (2022)",
        ],
        "summary": "Strongest overall profile. Has shipped Android and React apps on Firebase, a Unity game, won a first-place competition, and co-authored an accepted ASE 2026 paper. Comfortable with Agile, Scrum and Jira.",
        "strengths": "Full product delivery on mobile and web, research experience, presenting, team process.",
        "gaps": "No GitHub or portfolio link in the sheet or CV. No industry internship listed yet.",
        "next": "Natural technical mentor or co-lead. Could run a session on mobile development or getting into research. Ask for a GitHub or portfolio link.",
        "links": {"LinkedIn": "https://www.linkedin.com/in/osama-alghamdi-51555a34b"},
        "notes": [],
    },
    "remasalsulami962@gmail.com": {
        "en": "Remas Alsulami",
        "level": "Advanced",
        "focus": ["Full-stack", "Computer vision", "AR"],
        "skills": ["Java", "JavaScript", "Python", "C", "Node.js", "Express.js", "MongoDB", "MySQL", "WebSockets", "Tesseract.js", "WebXR", "Postman", "Git"],
        "projects": [
            "Medixa: full-stack drug-interaction platform with OCR (Tesseract.js) and real-time chat over WebSockets; Best Project certificate",
            "Atelier: digital art marketplace with WebXR augmented-reality previews",
            "Flight Ticket Booking System: Java Swing desktop app; team leader",
        ],
        "experience": [
            "Absher Tuwaiq Hackathon",
            "Project exhibitions: \"Wajhatuna Tahki\", UJ IoT Exhibition",
        ],
        "summary": "Deepest web engineering profile on the track: Node and Express backends, real-time WebSockets, OCR and WebXR, and an award for project quality. Has led a development team.",
        "strengths": "Backend and real-time features, integrating unusual tech (CV, AR), team leadership.",
        "gaps": "No internship or industry experience listed. No deployment or cloud work mentioned.",
        "next": "Strong mentor or technical lead for a track project. Point toward internships, deployment, and open-source contributions.",
        "links": {"GitHub": "https://github.com/Rema230Al", "LinkedIn": "https://www.linkedin.com/in/remas-alsulami-859569380"},
        "notes": ["Email on CV (remasnalsulami@gmail.com) differs from the sheet."],
    },
    "saramz4500@gmail.com": {
        "en": "Sara Alzahrani",
        "level": "Intermediate",
        "focus": ["Frontend", "UI/UX", "Product"],
        "skills": ["Java", "HTML", "CSS", "JavaScript", "Firebase", "Figma", "Usability testing", "Manual testing"],
        "projects": [
            "Alhamna School website with an admin dashboard for evaluation results",
            "Palette Muse: color palette generator using an external API, with CSS export",
            "Nasaq: event planning website with service packages",
            "Brain Gain: daily challenges website",
            "Nusuk enhancement: points system for Hajj and Umrah compliance",
        ],
        "experience": [
            "Digital Transformation Hackathon 2025 · Hajj Logistics Hackathon 2025",
            "Entrepreneurship Bootcamp 2025",
            "Hajj & Umrah Conference 2025 · AI & IoT innovation conference 2025",
        ],
        "summary": "Ships many small-to-mid web projects, including an admin dashboard and an API-driven tool. Has a clear career direction toward product management and UX.",
        "strengths": "Consistent project output, product thinking, user testing, hackathon experience.",
        "gaps": "No backend or database work beyond Firebase. English is self-rated as \"decent\".",
        "next": "Pair with a backend-strong member on a full-stack build. Give product-owner roles in track projects.",
        "links": {"GitHub": "https://github.com/saramz4500-spec"},
        "notes": ["GPA on CV is 4.75; sheet says 4.76."],
    },
    "jooryfaiz.1@gmail.com": {
        "en": "Jory F. Alharbi",
        "level": "Intermediate",
        "focus": ["Backend", "UI/UX"],
        "skills": ["Java", "Python", "SQL", "HTML/CSS/JS", "OOP", "Data structures", "JUnit", "REST APIs", "Git", "Figma"],
        "projects": [
            "TaskBee: Java task management system using OOP and SDLC practices (on GitHub)",
            "Personal resume website: HTML/CSS with Flexbox",
            "MedPlus: UI/UX research and interactive prototypes",
        ],
        "experience": [
            "Leader, Graphic Design Committee, Software Engineering Student Club (2023–2024)",
            "Courses: APIs & RESTful services (Satr/Tuwaiq, Apr 2026) · Python Basics (Coursera)",
        ],
        "summary": "Solid software-engineering fundamentals: OOP, SDLC, unit testing with JUnit and REST APIs, with work public on GitHub. One of the few members who mentions testing.",
        "strengths": "Engineering discipline (testing, requirements), Java, committee leadership.",
        "gaps": "Projects are academic scale. No portfolio link and no deployed web or mobile app.",
        "next": "Ready for a team project with a real API and database. Encourage a portfolio page to collect the GitHub work.",
        "links": {"GitHub": "https://github.com/JoryAlharbi9", "LinkedIn": "https://www.linkedin.com/in/joryalharbi/"},
        "notes": [],
    },
    "wsalasmayl363@gmail.com": {
        "en": "Wesal Ismail Ali",
        "level": "Intermediate",
        "focus": ["Frontend"],
        "skills": ["TypeScript", "JavaScript", "HTML", "CSS", "React", "Tailwind CSS", "Git", "AWS Elastic Beanstalk"],
        "projects": [
            "Movie Explorer: mobile-first movie search app on the TMDb API",
            "Weather Dashboard: async multi-day forecasts from WeatherAPI with a separate data-parsing layer",
        ],
        "experience": [],
        "summary": "Frontend-focused with a modern stack (TypeScript, React, Tailwind) and some deployment exposure on AWS. Projects show care for keeping data logic apart from the UI.",
        "strengths": "Modern frontend stack, clean architecture instincts, API integration.",
        "gaps": "Only two projects, both vanilla JS. No React project or backend shown. No experience section.",
        "next": "Build one React project end to end. Good helper for frontend workshops.",
        "links": {"Portfolio (from CV)": "https://we2004.github.io/my-portfolio/"},
        "notes": ["Sheet portfolio link is a Google Doc; the CV links a GitHub Pages portfolio. Both are listed."],
    },
    "jouryfa124@gmail.com": {
        "en": "Joury Almutairi",
        "level": "Intermediate",
        "focus": ["Frontend", "Mobile", "IoT", "UI/UX"],
        "skills": ["Python", "Java", "C", "Flutter", "Front-end development", "Figma", "OOP", "Agile"],
        "projects": [
            "Mali: personal finance mobile app in Flutter (budgets, expense tracking)",
            "Smart IV Monitoring System: IoT team project monitoring IV fluid levels",
            "Nasaq: event planning app designed and prototyped in Figma",
        ],
        "experience": [
            "Front-End Web Developer, GDG on Campus (Mar 2026–present)",
            "PR Member, GDG on Campus · PR Administrator, Bashoosh Volunteering Team",
            "Training: Full-Stack JavaScript (Satr) · HCIA-IoT (Huawei) · UI/UX Bootcamp",
        ],
        "summary": "Active as a frontend developer in GDG, with a Flutter mobile app and an IoT team project. Broad exposure across web, mobile and hardware.",
        "strengths": "Range across platforms, real team development in GDG, design skills.",
        "gaps": "Web stack isn't named (no JS or React listed despite the full-stack JS course). No backend project.",
        "next": "Help narrow the breadth into one focus. A JavaScript full-stack project would build on the Satr track.",
        "links": {"LinkedIn": "https://www.linkedin.com/in/joury-almutairi-938b37334"},
        "notes": [],
    },
    "asma.aljadani01@gmail.com": {
        "en": "Asma Aljadani",
        "level": "Intermediate",
        "focus": ["Full-stack"],
        "skills": ["Java", "Python", "C", "SQL", "HTML", "CSS", "JavaScript", "Node.js", "MySQL", "Git", "Figma"],
        "projects": [
            "Hajj & Umrah Platform: full-stack app with Node.js server, MySQL and form validation",
            "Motivational Quotes app: fetches from an external API with AJAX",
        ],
        "experience": [
            "Courses: AI Python Basics (Michigan) · Introductory AI (KAUST) · Web Development (IBM)",
        ],
        "summary": "One of the few with a true full-stack project: frontend, Node.js server logic and a MySQL database. Computer Science major with fundamentals in several languages.",
        "strengths": "End-to-end web development, databases, broad CS base.",
        "gaps": "Only two projects. No framework (React, Express) or deployment shown. No work or club experience listed.",
        "next": "Ready to lead a small team on a mid-size build. Introduce a framework and deployment.",
        "links": {"GitHub": "https://github.com/AsmaAljadani01", "LinkedIn": "https://www.linkedin.com/in/asma-aljadani01"},
        "notes": [],
    },
    "yalkhamesi2@gmail.com": {
        "en": "Yamam Alkhamesi",
        "level": "Developing",
        "focus": ["Full-stack", "IoT", "Leadership"],
        "skills": ["Frontend & backend integration", "UI/UX", "XAMPP", "ESP32 (basic)", "GitHub", "VS Code"],
        "projects": [
            "PillMate (Jul 2025)",
            "LUME (Sep–Dec 2025)",
            "Book Finder (Apr–May 2025)",
            "The Recipes Hub (Jan–May 2025)",
        ],
        "experience": [
            "Leader, Management & Planning Department, Bashosh Volunteer Team (Nov 2025–Apr 2026)",
            "Trainee, Robotics Engineering Camp, Mashorah for Research and Innovation (Jun–Jul 2025)",
        ],
        "summary": "Strong planner and team leader with four projects and a robotics camp. The CV lists project names without stacks or details, so technical depth is hard to judge. The portfolio should fill that in.",
        "strengths": "Leadership and planning, hardware-software exposure, IELTS 7.0.",
        "gaps": "No programming languages named. Project descriptions are missing.",
        "next": "Look at the portfolio together and ask for one project write-up. Could co-organize track events.",
        "links": {},
        "notes": [],
    },
    "farah2000jihad1@gmail.com": {
        "en": "Farah Shakh Alnajareen",
        "level": "Developing",
        "focus": ["UI/UX", "Mobile"],
        "skills": ["Figma", "Java", "C", "Python", "Dart", "Flutter (learning)", "MS Office"],
        "projects": [],
        "experience": [
            "UI/UX Designer, ATC Company (Jun–Jul 2025)",
            "1st place, Sustainability Towards Development Hackathon",
            "Finalist, Technology Challenge for Quranic Sciences",
            "INJAZ Project Management · Monsha'at Entrepreneurship Week · UI/UX Bootcamp",
        ],
        "summary": "Design-led, with real industry exposure (UI/UX internship) and a hackathon win. Coding is at the learning stage; currently picking up Flutter.",
        "strengths": "UI/UX in a real client setting, hackathon performance, GPA 4.98.",
        "gaps": "No coding projects listed. No GitHub or portfolio.",
        "next": "Good match for a Flutter build where design is the entry point. Pair with a developer to turn designs into working screens.",
        "links": {"LinkedIn": "https://www.linkedin.com/in/farah-shikh-alnajareen-490427374"},
        "notes": ["CV says second year; sheet says third year (the CV may be older)."],
    },
    "mayaralalwan@gmail.com": {
        "en": "Mayar Alalwan",
        "level": "Developing",
        "focus": ["Full-stack", "UI/UX"],
        "skills": ["Full-stack development", "Web app development", "UI/UX", "Figma"],
        "projects": [
            "Anah: gamified investment-learning platform; built the landing page front and back end, wrote requirements",
            "USES: university sports engagement system; requirements and feature development",
        ],
        "experience": [
            "GDG Web Development & Design team: UI design, web pages, backend integration",
            "Design Committee, Data Club · Media Committee, Aknaf Al-Haramain",
            "Courses: OCI AI Foundations · IBM Code Generation · IBM Project Management · Drones Fundamentals (Tuwaiq)",
        ],
        "summary": "Hands-on in GDG's web team connecting frontend and backend, plus requirements work on two platforms.",
        "strengths": "Team development experience, requirements documentation, design.",
        "gaps": "The CV names no languages or frameworks, so the actual stack is unclear. No GitHub or portfolio.",
        "next": "Ask which stack was used in GDG. A GitHub profile would make the level visible.",
        "links": {"LinkedIn": "https://www.linkedin.com/in/mayar-alalwan-2ba14b364"},
        "notes": [],
    },
    "kadogpshk7@gmail.com": {
        "en": "Khadijah Alamoudi",
        "level": "Developing",
        "focus": ["Databases", "UI/UX"],
        "skills": ["Java", "C", "SQL", "Oracle PL/SQL", "MySQL", "ERD design", "Figma", "Git"],
        "projects": [
            "Kids Learning Quiz: Java Swing GUI app with score tracking and saved results",
            "Storage Rental Management System: ER diagram, normalization, MySQL implementation",
            "ARSHIDNI: Figma prototype of an AI study-help app for UJ students",
        ],
        "experience": [
            "Certificates: IBM Project Management Fundamentals · IBM Code Generation with Granite",
        ],
        "summary": "Solid academic work across Java OOP, database design with normalization, and UI prototyping.",
        "strengths": "Database design, Java OOP, GPA 4.99.",
        "gaps": "No web stack. Projects are course-based. No GitHub or portfolio link.",
        "next": "Add web development (a Java or Node backend) to connect the database skills to a real app.",
        "links": {"LinkedIn": "https://www.linkedin.com/in/khadijah-alamooudi"},
        "notes": [],
    },
    "sadeemall84@gmail.com": {
        "en": "Sadeem Alsolmi",
        "level": "Developing",
        "focus": ["Frontend"],
        "skills": ["HTML", "CSS", "JavaScript", "C++", "Git"],
        "projects": [
            "Weather web app in JavaScript",
            "Car rental recommendation system in C++",
            "Personal resume website in HTML/CSS",
        ],
        "experience": [
            "Presenter certificate: Project Management Inside the Job Market, Drone Club",
        ],
        "summary": "Academic web and C++ projects with a public GitHub. Fundamentals are in place.",
        "strengths": "Web basics plus C++, work on GitHub.",
        "gaps": "Projects are course-scale. No framework, backend, or club experience listed.",
        "next": "Next step is a framework (React) or a first backend. A good fit for a guided team project.",
        "links": {"GitHub": "https://github.com/sadeemall84"},
        "notes": [],
    },
    "thishassna@gmail.com": {
        "en": "Hassna Alharbi",
        "level": "Developing",
        "focus": ["Frontend", "AI (interest)"],
        "skills": ["HTML", "CSS", "JavaScript", "Responsive design", "UI design", "Git"],
        "projects": [
            "Interactive Games Platform: frontend developer, GDG on Campus",
        ],
        "experience": [
            "Second Best Member, Web Design & Development Committee (GDG)",
            "Academic Excellence Certificate, four consecutive years",
        ],
        "summary": "Top academic record (GPA 5.00) and a recognized contributor in GDG's web committee. Frontend basics are in place; wants to move into AI.",
        "strengths": "Frontend, consistency, committee recognition.",
        "gaps": "One project listed. No Python or ML work yet despite the AI goal. No portfolio.",
        "next": "Bridge to AI with Python and a small ML project. Keep frontend as a strength.",
        "links": {"GitHub": "https://github.com/theinternetglrl", "LinkedIn": "https://www.linkedin.com/in/hassna-al-harbi-5048722a3"},
        "notes": [],
    },
    "lailajampi18@gmail.com": {
        "en": "Laila Jambi",
        "level": "Developing",
        "focus": ["Fundamentals", "Databases"],
        "skills": ["Java", "C++", "HTML", "SQL", "Git", "VS Code"],
        "projects": [
            "Library Management System (SQL)",
            "Personal website (HTML/CSS)",
            "Digital logic project",
        ],
        "experience": [
            "Seasonal Accommodation Officer, MCDC (Hajj season)",
            "Satr: Intro to HTML, Intro to Programming, C++, Robotics & Arduino",
            "IBM SkillsBuild: Code Generation with Granite, Project Management",
        ],
        "summary": "Early-stage developer who describes it plainly. Has touched several languages and finished many introductory courses.",
        "strengths": "Steady course completion, several languages started, work experience.",
        "gaps": "Projects are small. English is self-rated as basic, which can limit docs and resources.",
        "next": "A structured beginner-to-intermediate path: go deep in one language (Java) with a guided project. Arabic resources help.",
        "links": {},
        "notes": [],
    },
    "rmass2005@hotmail.com": {
        "en": "Rmaas Badr",
        "level": "Beginner",
        "focus": ["Leadership", "Design & Media"],
        "skills": ["C", "Java", "HTML/CSS", "SDLC concepts", "Project coordination"],
        "projects": [
            "Portfolio page (course assignment)",
        ],
        "experience": [
            "Department Leader, Publishing & Accounts, Bashosh Volunteer Team; \"Star of the Month\"",
            "Media & Photography Coordinator, Drone Club (Sep 2025–present)",
            "Project Management, EG VR team · Design & Media, AI Club · Media, Cybersecurity Club",
        ],
        "summary": "Strong organizer and team leader with a lot of club experience. The technical side is still coursework-level (C, Java) with no software projects listed.",
        "strengths": "Leadership, content and media, running teams and workflows.",
        "gaps": "No built projects beyond a course portfolio page.",
        "next": "Needs a first real project: give a guided beginner build. Use the organizing experience for track logistics or events.",
        "links": {"GitHub": "https://github.com/rmaasbadr", "LinkedIn": "https://linkedin.com/in/rmaas-badr"},
        "notes": ["Sheet portfolio link is a course assignment page (Assignment1)."],
    },
    "dialakk@hotmail.com": {
        "en": "Diala Alosaimi",
        "level": "Beginner",
        "focus": ["Design & Media", "UI/UX"],
        "skills": ["HTML", "Graphic design", "Video editing", "UI/UX"],
        "projects": [
            "Tayaqqun: AI-powered fake news detection concept; initial nominee, Saudi Media Forum Innovation Camp 2026",
        ],
        "experience": [
            "Design, Admissions & Judging organizer, Data Science for Logistics Hackathon (May 2026)",
            "Graphic designer: Saudi Surgical Bootcamp, Data Insights Community, EGVR Club, Data Science UJ",
            "Design & Content member, Drone Academy UJ",
        ],
        "summary": "Digital Media student with strong design and hackathon ideation experience. Programming is limited to HTML.",
        "strengths": "Visual design, event organizing, idea generation.",
        "gaps": "Major is outside computing (sheet marks major fit as \"No\"). No programming languages yet.",
        "next": "Start from web fundamentals (HTML, then CSS, then JS) with a design-heavy project. Could support track branding.",
        "links": {},
        "notes": ["GPA on CV is 4.4; sheet says 4.46."],
    },
    "khaled.alzaben.2@gmail.com": {
        "en": "Khalid Alzabin",
        "level": "Beginner",
        "focus": ["Hardware", "Research"],
        "skills": ["Autodesk Inventor", "3D modeling", "Engineering drawing", "Circuit analysis"],
        "projects": [
            "Eco-friendly bio-brick (Mawhiba, lead researcher)",
        ],
        "experience": [
            "Lead Researcher, Mawhiba (Oct 2024)",
            "Physics Club Leader, Alekhaa International Schools; mentored team to 2nd place in circuit analysis",
            "Science Fair winner, Most Creative Project (2023)",
        ],
        "summary": "Electrical Engineering student aiming for semiconductor engineering. Strong research and mentoring record from school, with no programming on the CV.",
        "strengths": "Research, engineering thinking, peer mentoring, IELTS 7.",
        "gaps": "No programming languages or software projects.",
        "next": "Start with Python or C aimed at hardware. An Arduino or ESP32 project connects programming to the semiconductor goal.",
        "links": {},
        "notes": ["CV says freshman; sheet says second year."],
    },
    "ritajsaad2005@hotmail.com": {
        "en": "Ritaj Alharthi",
        "level": "Beginner",
        "focus": ["Networks"],
        "skills": ["C++ (basic)", "Java (basic)", "MS Office", "Google Workspace", "Digital marketing"],
        "projects": [],
        "experience": [],
        "summary": "Third-year Computer Engineering & Networks student with basic C++ and Java. The CV lists no projects or experience.",
        "strengths": "Soft skills listed: communication, teamwork, fast learner.",
        "gaps": "No projects, activities, or GitHub.",
        "next": "Start with a guided first project. Find out what draws them (networks, security, web) and build from there.",
        "links": {},
        "notes": [],
    },
    "yaramran16@gmail.com": {
        "en": "Yara Omran",
        "level": "Beginner",
        "focus": ["Fundamentals"],
        "skills": ["C (basics)", "Algorithms & problem solving (basics)", "Computer & network engineering basics"],
        "projects": [],
        "experience": [],
        "summary": "First-year Computer Engineering & Networks student with a 5.00 GPA and early C fundamentals. Lists explaining and simplifying concepts as a strength. Interests: AI, cybersecurity, data science. Speaks Arabic, Turkish and English.",
        "strengths": "Academic strength, explaining ideas to others, fast learner.",
        "gaps": "No projects yet, which is expected in first year.",
        "next": "Beginner cohort with a first mini-project. The explaining strength could make them a good study-group facilitator later.",
        "links": {},
        "notes": [],
    },
    "queenjori2007@gmail.com": {
        "en": "Jory Bahareth",
        "level": "Beginner",
        "focus": ["AI/ML (interest)", "Cybersecurity"],
        "skills": ["Python", "C", "Java", "UI/UX fundamentals", "Basic cybersecurity", "Basic data analysis"],
        "projects": [
            "Smart Library Management System (C): live availability, student borrowing lookup",
            "Clinic Management System (C): structs and arrays for patient and physician records",
        ],
        "experience": [
            "CS50 Introduction to Cybersecurity (HarvardX)",
            "AI Skills Bootcamp · Excel Data Analysis Bootcamp · many AI and robotics workshops (70+ certificates per LinkedIn)",
        ],
        "summary": "Very eager learner with a large number of workshops and certificates, plus two structured C projects from the preparatory year. Interested in machine learning.",
        "strengths": "Drive to learn, breadth of exposure, structured C projects.",
        "gaps": "Early stage. No Python or ML project yet.",
        "next": "Turn the workshop energy into one Python project, then a beginner ML path.",
        "links": {"LinkedIn": "https://www.linkedin.com/in/jorybahareth"},
        "notes": ["CV says preparatory year; sheet says second year."],
    },
}

# Members whose CV submission exists but could not be analyzed.
INCOMPLETE_NOTES = {
    "hayaaziz-1423@gmail.com": "The submitted \"CV\" is an academic excellence certificate (Excellent grade, two semesters, 2025/26), not a CV.",
}
